Create Header and greet component for index.html and add linters config
Artufelii/microverse-portfolio pull request #1
Opened 2023-03-23 18:03 UTC by Artufelii

This is the first integration to the repository, I added a index file with header and greet component, and also linters configuration

2023-03-23 19:22 UTC, topeogunleye reviewed
Hi @Artufelii, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that doesn't follow the project requirements, as it is clearly stated that students need to choose 1 of the provided templates [here](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-23 19:31 UTC, Artufelii commented
thanks for the help @topeogunleye  I'll do the changes

2023-03-24 00:09 UTC, Strangeal requested changes
Hi @Artufelii, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 00:09 UTC, Strangeal commented on index.html
> +				<h1>Hi! I'm a web developer</h1>
Please make sure to follow the Figma template exactly and remember to include your `name`.
Original:
<img width="303" alt="Screenshot 2023-03-23 at 17 01 05" src="https://user-images.githubusercontent.com/107192076/227390336-2ed9ac9d-3739-4504-81b5-3bb70ee3d9cb.png">

Yours:
<img width="327" alt="Screenshot 2023-03-23 at 16 59 53" src="https://user-images.githubusercontent.com/107192076/227390380-c2a05b0d-6ed5-4a6b-a0c4-c48cee4ce48e.png">

2023-03-24 00:09 UTC, Strangeal commented on index.html
> +				</div>
Please use `ul` and `li` tags to display the icons and also each icon should have an `a` tag so it can be clicked on to your social media handles.

2023-03-24 01:44 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @Artufelii, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 01:53 UTC, merged